# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeorder', '0003_auto_20161116_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(help_text='A label for URL config.', max_length=31, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(help_text='A label for URL config.', max_length=31, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='table',
            name='slug',
            field=models.SlugField(help_text='A label for URL config.', max_length=31, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, verbose_name='date ordered'),
        ),
    ]
