# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placeorder', '0005_auto_20161216_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicorder',
            name='table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='placeorder.Table'),
            preserve_default=False,
        ),
    ]
